server:
  port: 8082

spring:
  application:
    name: scouting-service

  mongodb:
    uri: mongodb://root:password@localhost:27017/scouting_db?authSource=admin

  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/scouting_db?authSource=admin