server:
  port: 8082

spring:
  application:
    name: scouting-service

  mongodb:
    uri: ${SPRING_MONGODB_URI:mongodb://root:password@localhost:27017/scouting_db?authSource=admin}

integration:
  player-service:
    base-url: ${PLAYER_SERVICE_URL:http://localhost:8081}
